// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBWYpkK6p9YAjTj2hwKzcu3VITUNB-qUo',
    appId: '1:725140031864:web:f6ba2f4635bcdc36f7e08d',
    messagingSenderId: '725140031864',
    projectId: 'stylesphere-e3ab7',
    authDomain: 'stylesphere-e3ab7.firebaseapp.com',
    storageBucket: 'stylesphere-e3ab7.firebasestorage.app',
    measurementId: 'G-Y3GD1LBPQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4szWweKrQGAcn54mwXXMF7RVKiH9O2g',
    appId: '1:725140031864:android:d59647de6ff43f9df7e08d',
    messagingSenderId: '725140031864',
    projectId: 'stylesphere-e3ab7',
    storageBucket: 'stylesphere-e3ab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzOJp3x8dOFEqHRR0IALgGPtQ_gUsc6U',
    appId: '1:725140031864:ios:46c085146af1922af7e08d',
    messagingSenderId: '725140031864',
    projectId: 'stylesphere-e3ab7',
    storageBucket: 'stylesphere-e3ab7.firebasestorage.app',
    iosBundleId: 'com.example.stylesphereApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzOJp3x8dOFEqHRR0IALgGPtQ_gUsc6U',
    appId: '1:725140031864:ios:46c085146af1922af7e08d',
    messagingSenderId: '725140031864',
    projectId: 'stylesphere-e3ab7',
    storageBucket: 'stylesphere-e3ab7.firebasestorage.app',
    iosBundleId: 'com.example.stylesphereApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBWYpkK6p9YAjTj2hwKzcu3VITUNB-qUo',
    appId: '1:725140031864:web:f292b1b1026abbe4f7e08d',
    messagingSenderId: '725140031864',
    projectId: 'stylesphere-e3ab7',
    authDomain: 'stylesphere-e3ab7.firebaseapp.com',
    storageBucket: 'stylesphere-e3ab7.firebasestorage.app',
    measurementId: 'G-9Y4PPWL8E8',
  );
}
